FROM registry.tonberry.org/tonberry/torch:1.0
ARG PYTHON_MODULE=torch_diffusion
RUN conda run -n torch pip install neptune slack-sdk hydra-core
WORKDIR /var/torch/torch-diffusion
ENTRYPOINT ["conda", "run", "--no-capture-output", "-n", "torch", "python", "-m", "torch_diffusion"] 
# ENTRYPOINT ["sleep", "1000"]
