apiVersion: batch/v1
kind: Job
metadata:
  name: diffusion-inference-job
spec:
  template:
    spec:
      nodeSelector:
        gpu: "true"
      containers:
        - image: registry.tonberry.org/tonberry/diffusion-inference:latest
          name: diffusion-inference-job
          resources:
            limits:
              nvidia.com/gpu: 1
              memory: "10Gi"
              cpu: "6"
            requests:
              nvidia.com/gpu: 1
              memory: "5Gi"
              cpu: "4"
          env:
            - name: INFERENCE_ENABLED
              value: True
            - name: MODEL_HEIGHT
              valueFrom:
                configMapKeyRef:
                  name: diffusion-config
                  key: model.height
            - name: MODEL_WIDTH
              valueFrom:
                configMapKeyRef:
                  name: diffusion-config
                  key: model.width
            - name: NEPTUNE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: neptune-api-key
                  key: NEPTUNE_API_KEY
            - name: SLACK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: slack-token
                  key: SLACK_TOKEN
            - name: SLACK_CHANNELS_MONITORING
              valueFrom:
                secretKeyRef:
                  name: slack-channels-monitoring
                  key: SLACK_CHANNELS_MONITORING
          volumeMounts:
            - name: diffusion-inference-job-persistent-storage
              mountPath: /var/torch/
            - name: dshm
              mountPath: /dev/shm
      volumes:
        - name: diffusion-inference-job-persistent-storage
          persistentVolumeClaim:
            claimName: diffusion-inference-job-claim
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 8Gi
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      restartPolicy: Never # Ensures that the Pod does not restart on failure
  # Specify backoffLimit to control the number of retries
  backoffLimit: 2
