model:
  height: ${oc.env:MODEL_HEIGHT, 192}
  width: ${oc.env:MODEL_WIDTH, 128}
  features: ${oc.env:MODEL_FEATURES, 256}
neptune:
  api_key: ${oc.env:NEPTUNE_API_TOKEN, null}
preprocess:
  enabled: ${oc.env:PREPROCESS_ENABLED, False}
  output_dir: ${oc.env:PREPROCESS_OUTPUT_DIR, "../preprocessed_data"}
  input_dir: ${oc.env:PREPROCESS_INPUT_DIR, "../data"}
  samples_per_image: ${oc.env:PREPROCESS_SAMPLES_PER_IMAGE, "5"}
slack:
  token: ${oc.env:SLACK_TOKEN, null}
  channels:
    monitoring: ${oc.env:SLACK_CHANNELS_MONITORING, null}
training:
  max_epochs: ${oc.env:TRAINING_MAX_EPOCHS, 100}
  batch_size: ${oc.env:TRAINING_BATCH_SIZE, 32}
  learning_rate: ${oc.env:TRAINING_LEARNING_RATE, 0.001}
  num_workers: ${oc.env:TRAINING_NUM_WORKERS, 2}
  checkpoint_dir: ${oc.env:TRAINING_CHECKPOINT_DIR, "./model_checkpoints" }
  checkpoint: ${oc.env:TRAINING_CHECKPOINT_DIR, null}
  accumulate_grad_batches: ${oc.env:TRAINING_ACCUMULATION_GRAD_BATCHES, 7}
  gradient_clip_val: ${oc.env:TRAINING_GRADIENT_VAL, 0.5}
  stochastic_weight_averaging: ${oc.env:STOCHASTIC_WEIGHT_AVERAGING, 1e-2}
  validation_split: ${oc.env:TRAINING_VALIDATION_SPLIT, 0.2}
  test_split: ${oc.env:TRAINING_TEST_SPLIT, 0.1}
  early_stopping:
    enabled: ${oc.env:TRAINING_EARLY_STOPPING_ENABLED, False}
    patience: ${oc.env:TRAINING_EARLY_STOPPING_PATIENCE, 5}
    min_delta: ${oc.env:TRAINING_EARLY_STOPPING_MIN_DELTA, 0.0001}
inference:
  enabled: ${oc.env:INFERENCE_ENABLED, False}
diffusion:
  beta1: 1e-4
  beta2: 0.02
  timesteps: 500
