apiVersion: v1
kind: PersistentVolume
metadata:
  name: diffusion-job-volume
  namespace: torch
spec:
  storageClassName: ""
  volumeMode: Filesystem
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  local:
    path: /mnt/sd/torch/torch-diffusion
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - jetson00